club/urls.py
from django.conf.urls import url

from django.contrib.auth import views as auth_views



from . import views



urlpatterns = [
	url(r'adroit/$', views.adroit, name='adroit'),
	url(r'wheels/$', views.wheels, name='wheels'),
	url(r'laser/$', views.laser, name='laser'),
	url(r'sound/$', views.sound, name='sound'),
	url(r'project/$', views.project, name='project'),
	url(r'contact/$', views.contact, name='contact'),
	url(r'$', views.index, name='index'),
]

clubsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin



urlpatterns = [

    url(r'^', include('club.urls', namespace="club")),
    url(r'^admin/', admin.site.urls),

]

club/models.py
from django.db import models

# Create your models here.

club/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field
from crispy_forms.bootstrap import FormActions

class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    email_subject = forms.CharField(required=True)
    content = forms.CharField(
        required=True,
        widget=forms.Textarea
    )
    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-sm-2'
        self.helper.field_class = 'col-sm-4'
        self.helper.layout = Layout(
            Field('contact_name', css_class='form-control'),
            Field('contact_email', css_class='form-control'),
            Field('email_subject', css_class='form-control'),
            Field('content', css_class='form-control'),
            FormActions(Submit('submit', 'Submit', css_class='btn btn-primary'))
        )

club/views.py
from django.shortcuts import render
from .forms import *
import sendgrid
import os

def index(request):
	return render(request, "index.html")

def contact(request):
	response = None
	if request.method == "GET":
		form = ContactForm()
	else:
		form = ContactForm(data=request.POST)
		if form.is_valid():
			contact_name = form.cleaned_data['contact_name']
			contact_email = form.cleaned_data['contact_email']
			email_subject = form.cleaned_data['email_subject']
			content = form.cleaned_data['content']

			sg = sendgrid.SendGridAPIClient(apikey=os.environ.get('SENDGRID_API_KEY'))
			data = {
				"personalizations": [{
						"to": [{"email": "jes3cu@virginia.edu"}],
						"subject": email_subject
					}],
				"from": {"email": contact_email},
				"content": [{
						"type": "text/plain",
						"value": content
				}]
			}
			response = sg.client.mail.send.post(request_body=data)
			form = ContactForm()
	return render(request, "contact.html", {'form':form, 'email_sent':response})

def project(request):
	return render(request, "project.html")

def adroit(request):
	title = "ADROIT Assistive Device"
	picture = "Picture Here"
	abstract = "Lorem ipsum dolor sit amet, ad eam dicat simul eligendi, ei malorum probatus eam. Feugiat accusamus scripserit mel id. Et usu quidam maluisset. Cum persius feugait detracto in. Ius quaeque accusam appetere et, et mei quem habemus, quo ponderum vivendum ea. Ut mea facilis volutpat constituto, et sea lucilius consequuntur, essent facilisi dissentiet cum ex.  Sit dolor iriure no, vim choro praesent ex. No option saperet lucilius has. Omnes persius patrioque duo ut. Ad vel discere perfecto imperdiet, at est unum prima possit. At ius melius albucius insolens, ne utroque percipitur pro, nominavi ponderum eu ius. Eam id debet detracto principes, falli aeque constituto eam te, per te clita altera."
	team_members = {'John Doe':'jd9pp', 'Foo Bar':'fb2al'}
	readings = ['Wiki', 'Other']
	return render(request, "project.html", {'title':title, 'picture':picture, 'abstract':abstract, 'team_members':team_members, 'readings':readings})

def wheels(request):
	title = "Automated Training Wheels"
	picture = "Picture Here"
	abstract = "Lorem ipsum dolor sit amet, everti sensibus quo ut, an brute corrumpit usu. Ad augue ceteros usu, omnis tempor et eos. No has prima autem petentium, his dicant aeterno nominati in. Per ei molestie torquatos, vis suas timeam consulatu ei. Quo congue sententiae an, wisi debet liberavisse no vel.  Habeo suavitate dissentiet no sed. Vim minim epicurei partiendo ei, has ne sapientem consectetuer. At posse legimus sit, quo ei maluisset ullamcorper, velit nonumy eum in. Ius mutat doctus ea, his ex vidisse perpetua maiestatis, an nec albucius scaevola vivendum. Natum tation sensibus ea mel."
	team_members = {'Guy Fieri':'gf2el', 'Jackson Galaxy':'jg7ug'}
	readings = ['Wiki', 'More']
	return render(request, "project.html", {'title':title, 'picture':picture, 'abstract':abstract, 'team_members':team_members, 'readings':readings})

def laser(request):
	title = "Laser Line Shield"
	picture = "Picture Here"
	abstract = "Vocent phaedrum ei vis. Cum quaestio expetendis scribentur in, ipsum eloquentiam ut eam. Ea his oratio suavitate. Iudicabit accommodare ne sed, indoctum torquatos te cum, stet maiorum ex nam. In falli sadipscing nec, vis an tale sonet eloquentiam, numquam legimus vel te. Mutat inani interpretaris sea te, mei ut rebum populo tritani, tibique oportere reprimique ius ad.  Fuisset lucilius ex sed, cu animal nominati delicata vel. Qui suas nobis munere id, te vis enim case, te per dicit facilis. Reque assentior in eam, at porro definiebas usu. Duo id inani platonem posidonium, dolor mollis qualisque duo ex. Impetus eripuit suscipiantur ne sed, ad movet paulo deleniti ius. Ex diam quidam quo."
	team_members = {'This Guy':'tg3gt', 'That Girl':'gt4tg'}
	readings = ['Wiki', 'Reading']
	return render(request, "project.html", {'title':title, 'picture':picture, 'abstract':abstract, 'team_members':team_members, 'readings':readings})

def sound(request):
	title = "Sound Wave Module"
	picture = "Picture Here"
	abstract = "Lorem ipsum dolor sit amet, denique rationibus mei ad. Eam te melius latine atomorum. Harum oratio forensibus ad eam. Et his tamquam numquam, ei nihil populo altera usu.  Vim ne congue utroque, ipsum verear ne eum. Eu congue democritum cum, enim luptatum ex has. Veri minim nec in. Nonumy mandamus eu vis, quo in qualisque laboramus. Eleifend cotidieque vituperatoribus ut eos, ne eam dicant explicari."
	team_members = {'He Is':'hi7ae', 'She Is':'si8rt'}
	readings = ['Wiki', 'Him']
	return render(request, "project.html", {'title':title, 'picture':picture, 'abstract':abstract, 'team_members':team_members, 'readings':readings})

club/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.css" rel="stylesheet" type="text/css" />
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js"></script>
    </head>
    <body>
    {% block navbar %}

    {% endblock %}
        <div>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

club/templates/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} .
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
              <div class="jumbotron text-center">
                  <h1>Contact Us</h1>
              </div>
            {% if email_sent %}
                <div class="alert alert-success alert-dismissible fade in" role="alert">
                    <button class="close" aria-label="Close" type="button" data-dismiss="alert">
                        <span aria-hidden="true">×</span>
                    </button>
                    <strong>Thanks for your email!</strong> We'll be in touch soon.
                </div>
            {%  endif %}
            <form role="form" action="{% url 'club:contact'%}" method="post">
                <p><b>* represents a required field</b></p>
                {% crispy form %}
            </form>

          <br><br>

          </div>
      </div>
{% endblock %}}

club/templates/index.html
{% extends 'base.html' %}

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
               <div class="jumbotron text-center">
                  <h1>Hoos Invent</h1>
                  <p>...</p>
                  <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
               </div>
               <div class="alert alert-info">
                Although this organization has members who are University of Virginia students and may have University employees associated or engaged in its activities and affairs, the organization is not a part of or an agency of the University.  It is a separate and independent organization which is responsible for and manages its own activities and affairs.  The University does not direct, supervise or control the organization and is not responsible for the organization’s contracts, acts or omissions.
               </div>
        </div>
    </div>

{% endblock %}}

club/templates/navbar.html
<!-- Top Navbar -->
<nav class="navbar navbar-default navbar-static-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{% url 'club:index' %}" class="navbar-brand">Hoos Invent</a>
        </div>

        <ul class="nav navbar-nav navbar-left">
            <li><a href="#">About Us</a></li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    Current Projects<span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'club:adroit' %}">ADROIT Assistive Device</a></li>
                    <li><a href="{% url 'club:wheels' %}">Automated Training Wheels</a></li>
                    <li><a href="{% url 'club:laser' %}">Laser Line Shield</a></li>
                    <li><a href="{% url 'club:sound' %}">Sound Wave Module</a></li>
                </ul>
            </li>
            <li><a href="#">Past Projects</a></li>
            <li><a href="#">Executive Board</a></li>
            <li><a href="{% url 'club:contact' %}">Contact Us</a></li>
        </ul>
        <!-- Collect the nav links, forms, and other content for toggling -->
    </div>
        <!-- /.navbar-collapse -->
</nav>

club/templates/project.html
{% extends 'base.html' %}

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="jumbotron text-center">
             <h1>{{ title }}</h1>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-sm-4">
            <h1>{{ picture }}</h1>
        </div>
        <div class="col-sm-8">
            <p>
                {{ abstract }}
            </p>
        </div>
    </div>
    <hr>
    <div class="row">
        <table style="width: 100%;border: 1px solid black">
            <tr>
                <th colspan="2"><center>Team</center></th>
            </tr>
            <tr>
                <th>Name</th>
                <th>ID</th>
            </tr>
            {% for name, id in team_members.items %}
                <tr>
                    <td>{{ name }}</td>
                    <td>{{ id }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <hr>
    <div class="row">
        <h2>Further Reading:</h2>
        <ul>
            {% for reading in readings %}
                <li>{{ reading }}</li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}